import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Nav from '@/components/Nav'
import Hero from '@/components/Hero'
import Portfolio from '@/components/Portfolio'
import Contact from '@/components/Contact'

export default function Home() {
  return (
    <>
      <Head>
        <title>johnmonk.dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <header className={styles.header}>
            <div className={`container ${styles.content}`}>
              <a className={styles.logo} href="https://johnmonk.dev/">johnmonk.dev</a>
              <Nav />
            </div>
        </header>
        <Hero />
        <Portfolio />
        <Contact />
    </>
  )
}
